language: go

sudo: required

go:
    - 1.6.2
    - tip

env:
    - COMPOSE_VERSION=1.7.1


before_install:
    - curl -sSL https://get.docker.com/ | sh
    - sudo docker version
    - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - docker-compose version
    # - sudo docker-compose up -d
    - sudo docker network ls

install:
    - go get github.com/tools/godep
    - godep version

before_script:
    - sudo docker run --rm hello-world

script:
    - echo "hello! ${USER}"

after_success:
    - echo "success!"